/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passpoetmanagmentsystem;

//import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;

import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author nethm
 */
public class ApplicantData extends javax.swing.JFrame {
    

    
    

    /**
     * Creates new form ApplicantData
     */
    public ApplicantData() {
        initComponents();
        
    
    }
    
    /**public void showRecord(){
        try{
            pst = con.prepareStatement("select * from application");
            rs = pst.executeQuery();
             ResultSetMetaData rsm = (ResultSetMetaData) rs.getMetaData();
            int n = rsm.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) table.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector obj = new Vector();
                for(int i = 1; i<=n ; i++){
                obj.add(rs.getString(1));
                obj.add(rs.getString(2));
                obj.add(rs.getString(3));
                obj.add(rs.getString(4));
                obj.add(rs.getString(5));
                obj.add(rs.getString(6));
                obj.add(rs.getString(7));
                obj.add(rs.getString(8));
                obj.add(rs.getString(9));
                    
                }
                df.addRow(obj);
            }
            
        }catch(Exception ex){
           System.out.println(ex);
           
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nica = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        nic = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        gen = new javax.swing.JTextField();
        cty = new javax.swing.JTextField();
        adress = new javax.swing.JTextField();
        bday = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        cn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nica.setText("nic");
        jPanel1.add(nica, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 40, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("Applicant Details For Manual Creation");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 750, -1));

        fname.setText("firstName");
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        lname.setText("lastName");
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        gender.setText("gender");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        city.setText("city");
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        address.setText("address");
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        birthday.setText("birthday");
        jPanel1.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        contact.setText("contact");
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        email.setText("email");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));
        jPanel1.add(nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 400, -1));

        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 400, 20));
        jPanel1.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 400, -1));
        jPanel1.add(gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 400, -1));

        cty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctyActionPerformed(evt);
            }
        });
        jPanel1.add(cty, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 400, -1));
        jPanel1.add(adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 400, -1));

        bday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdayActionPerformed(evt);
            }
        });
        jPanel1.add(bday, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 400, -1));
        jPanel1.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 400, -1));
        jPanel1.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 400, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/passpoetmanagmentsystem/assets/blue .jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 850, 350));

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 140, -1));

        searchbtn.setText("View Details");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 140, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/passpoetmanagmentsystem/assets/blue .jpeg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 850, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctyActionPerformed

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdminFunctions ap = new AdminFunctions();
        ap.show();
        dispose();// TODO add your handling code here:

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:

        Connection conn = Connectdb.connect();
        try
        {
             
            
            
            String query = "Select * from connectdb.application where nic = ?";
            PreparedStatement pst = conn.prepareStatement(query);

            pst.setString(1,txtsearch.getText());

            ResultSet re = pst.executeQuery();

            re.next();
            
            
             


        nic.setText(re.getString("nic"));
            fn.setText(re.getString("FirstName"));
            ln.setText(re.getString("LastName"));
            gen.setText(re.getString("gender"));
            cty.setText(re.getString("province"));
            adress.setText(re.getString("Address"));
            bday.setText(re.getString("dob"));
            em.setText(re.getString("Email"));
            cn.setText(re.getString("contact"));
            
            
          
           
             
            
            
            
            

        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this,"Ïnvalid nic");
            ApplicantData ad = new ApplicantData();
                ad.show();
                dispose();

            
        }

    }//GEN-LAST:event_searchbtnActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtsearchKeyPressed

    private void bdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicantData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicantData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicantData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicantData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicantData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField adress;
    private javax.swing.JTextField bday;
    private javax.swing.JLabel birthday;
    private javax.swing.JLabel city;
    private javax.swing.JTextField cn;
    private javax.swing.JLabel contact;
    private javax.swing.JTextField cty;
    private javax.swing.JTextField em;
    private javax.swing.JLabel email;
    private javax.swing.JTextField fn;
    private javax.swing.JLabel fname;
    private javax.swing.JTextField gen;
    private javax.swing.JLabel gender;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ln;
    private javax.swing.JLabel lname;
    private javax.swing.JTextField nic;
    private javax.swing.JLabel nica;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

    private Statement CreateStatement(int TYPE_SCROLL_INSENSITIVE, int CONCUR_READ_ONLY) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
