/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passpoetmanagmentsystem;

/**
 *
 * @author USER
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        administrator = new javax.swing.JLabel();
        administratorbutton = new javax.swing.JButton();
        applicant = new javax.swing.JLabel();
        applicantButton = new javax.swing.JButton();
        policebutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("Home Page.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 310, 60));

        administrator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/passpoetmanagmentsystem/assets/administrator.png"))); // NOI18N
        administrator.setText("jLabel2");
        jPanel1.add(administrator, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 150, 110));

        administratorbutton.setText("Administrator");
        administratorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administratorbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(administratorbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        applicant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/passpoetmanagmentsystem/assets/Applicant.png"))); // NOI18N
        jPanel1.add(applicant, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 210, 190));

        applicantButton.setText("Applicant");
        applicantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicantButtonActionPerformed(evt);
            }
        });
        jPanel1.add(applicantButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        policebutton.setText("Police");
        policebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(policebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/passpoetmanagmentsystem/assets/policeimage.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 140, 160));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/passpoetmanagmentsystem/assets/blue .jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 790, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applicantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicantButtonActionPerformed
        // TODO add your handling code here:
        ApplicantType appType = new ApplicantType();
        appType.show();
        
        dispose();
        
    }//GEN-LAST:event_applicantButtonActionPerformed

    private void administratorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administratorbuttonActionPerformed
        // TODO add your handling code here:
        AdminLogin al = new AdminLogin();
        al.show();
        dispose();
    }//GEN-LAST:event_administratorbuttonActionPerformed

    private void policebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policebuttonActionPerformed
        // TODO add your handling code here:
        PoliceLogin pl = new PoliceLogin();
        pl.show();
        dispose();
    }//GEN-LAST:event_policebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel administrator;
    private javax.swing.JButton administratorbutton;
    private javax.swing.JLabel applicant;
    private javax.swing.JButton applicantButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton policebutton;
    // End of variables declaration//GEN-END:variables
}
